typography_spectrum: 0.3539031457621604
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7674809233285487
  lightness: 0.10198939172551036
  saturation: 0
  rhythmicContrast: 0.4586591268889606
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0210314376745373
analytics:
  google: null
  facebook: null
  twitter: null
name: honza svasek
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: open butoh
description: 'enjoy, copy, remix & S H A R E...'
purpose: []
