name: butoh
favicon: null
layout_spectrum: 0.0210314376745373
typography_spectrum: 0.3539031457621604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7674809233285487
  lightness: 0.10198939172551036
  saturation: 0.5938078574836254
  rhythmicContrast: 0.4586591268889606
purpose: []
